version: '3'
services:
  #Database MySql
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - ./dump.sql:/docker-entrypoint-initdb.d/init.sql
       - db_data:/var/lib/mysql   
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - back  
  #WordPress CMS
  wordpress:
    depends_on:
      - db
    image: wordpress-grupo11:1.16
    restart: always
    volumes:
      - ./html:/var/www/html
      - ./cgi-bin:/usr/lib/cgi-bin
      - ./err:/var
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      #Java
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/default-java/bin:/usr/lib/jvm/default-java/db/bin
      JAVA_HOME: /usr/lib/jvm/default-java     
    ports:
      - '80:80'
    networks:
      - back
networks:
  back:
volumes:
  db_data:
